### ISSUE TITLE
Profile Page Edit problems

### ISSUE THREAD

**Issue by ArnoYan** [emielvanseveren/websecurityproject#13]
Als je 2 keer op EDIT knop drukt, verschijnen er 2 invulvelden ipv 1 op het scherm

**Comment by ThanathosBE** [comment]
zal vanmiddag es checkn ^^

**Comment by ThanathosBE** [comment]
Bedoel je de link "Add information"? zoja, lukt het me niet om het probleem te reproducen.
Kan je eventueel screenshotke nemen?

**Comment by ThanathosBE** [comment]
word afgehandeld in #17
