### ISSUE TITLE
PROFILE | EDIT

### ISSUE THREAD

**Issue by emielvanseveren** [emielvanseveren/websecurityproject#2]
### Wat moet er gebeuren

- de data die meegeven werd met php moet in javascript geopend worden. (ik dacht eerst de data in tekstvelden maar aangezien ze waarschijnlijk XSS kunnen toepassen omdat er vervolgens js op losgelaten wordt is het misschien beter met de info die we krijgen via php. 
- De data moet ipv in p tags zoals in html moeten vervolgens vervangen worden door inputs met als value die inhoud. Zodat wanneer de user klikt op de edit niet alles plots  leeg is en opnieuw ingevuld moet worden. 
- Hier moet ook gevalideerd worden zodat de user geen XSS kan op uitvoeren.
- Wanneer er op de knop OK gedrukt wordt moet de data dan opnieuw doorgestuurd worden met behulp van PHP.

**Comment by ThanathosBE** [comment]
PHP = OK voor edits, security later!

**Comment by ThanathosBE** [comment]
Zit reeds in php, sec is later (vanmiddag :p)
