### ISSUE TITLE
USER CREATION | BOT

### ISSUE THREAD

**Issue by emielvanseveren** [emielvanseveren/websecurityproject#4]
### Confirmation link

Om te voorkomen dat bots oneindig veel accounts aanmaken kunnen we gebruik maken van een confirmation e-mail.  Dit lost het probleem niet volledig op.. Daarom zouden we een soort van recaptcha via localhost moeten arrangeren. Normaal gezien is localhost captcha niet meer ondersteunt maar er zijn blijkbaar loopholes. 
--> Iemand kan zich hiermee bezighouden op de loginpage 👍

**Comment by Maxim-Seys** [comment]
Issue is fixed <script>alert(1)</script>
