### ISSUE TITLE
THEMA FORUM

### ISSUE THREAD

**Issue by emielvanseveren** [emielvanseveren/websecurityproject#5]
**Iemand een idee waar het algemeen thema voor ons forum kan zijn**`

**Comment by ThanathosBE** [comment]
een guestbook ofz.

**Comment by ThanathosBE** [comment]
OF we kunnen een" Post-Your-Code snippets here" maken :p (dan moeten we ook geen regex maken die code afstoot, maar eerder opslaan in db en niet laten uitvoeren (zoal vorigjaar)
